name: couchbase_dart
repository: https://github.com/blaugold/couchbase-dart
packages:
  - tool
  - packages/couchbase
  - packages/couchbase/example

ide:
  intellij: false

command:
  version:
    hooks:
      preCommit: melos run tool -- generate-version

scripts:
  format:
    run: dart format .
    description: Format the Dart codebase.

  format:check:
    run: dart format --set-exit-if-changed .
    description: Check if the Dart codebase is formatted.

  analyze:
    run: dart analyze --fatal-infos
    description: Analyze the Dart codebase.

  test:
    exec: dart test
    packageFilters:
      dirExists: test
    description: Run Dart tests.

  build:OpenSSL:
    run: cd native && dart build_openssl.dart

  build:libCouchbaseDart:
    run: cd native && dart build.dart

  build:bindings:
    run: |
      cd tool && \
      dart run tool:generate_bindings && \
      cd ../packages/couchbase && \
      ./tool/ffigen.sh

  initCouchbaseServer:
    run: ./init-couchbase-server.sh

  tool:
    run: cd tool && dart run tool:tool
