name: couchbase
description:
  Couchbase Server SDK for Dart. Couchbase is a distributed, scalable, NewSQL,
  document-oriented database.
version: 0.0.0
repository: https://github.com/blaugold/couchbase-dart
issue_tracker: https://github.com/blaugold/couchbase-dart/issues
homepage: https://github.com/blaugold/couchbase-dart/tree/main/packages/couchbase

environment:
  sdk: ^2.19.0

dependencies:
  collection: ^1.16.0
  ffi: ^2.0.1
  meta: ^1.8.0
  path: ^1.8.0
  solvent: ^0.1.1

dev_dependencies:
  checks: ^0.2.1
  ffigen: ^7.2.9
  lints: ^2.0.0
  test: ^1.21.0

ffigen:
  output: 'lib/src/lib_couchbase_dart.dart'
  name: LibCouchbaseDart
  description: 'Bindings for libCouchbaseDart'
  headers:
    entry-points:
      - '../../native/include/*.h'
    include-directives:
      - '**/native/include/*.h'
  llvm-path:
    - /opt/homebrew/opt/llvm
  functions:
    symbol-address:
      include:
        - '.*'
