name: couchbase
description: Couchbase SDK for Dart
version: 1.0.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  ffi: ^2.0.1
  meta: ^1.9.1
  path: ^1.8.3

dev_dependencies:
  checks: ^0.2.1
  ffigen: ^7.2.9
  lints: ^2.0.0
  test: ^1.21.0

ffigen:
  output: 'lib/src/lib_couchbase_dart.dart'
  name: LibCouchbaseDart
  description: 'Bindings for libCouchbaseDart'
  headers:
    entry-points:
      - '../../native/include/*.h'
    include-directives:
      - '**/native/include/*.h'
  llvm-path:
    - /opt/homebrew/opt/llvm
  functions:
    symbol-address:
      include:
        - '.*'
