name: CI

on:
  push:
    branches: [main]
    tags-ignore: ['**']
  pull_request:
    branches: [main]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-13
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Docker
        if: runner.os == 'macOS'
        run: |
          brew install docker
          brew install docker-compose
          mkdir -p ~/.docker/cli-plugins
          ln -sfn $(brew --prefix)/opt/docker-compose/bin/docker-compose ~/.docker/cli-plugins/docker-compose
          brew install colima
          colima start

      - name: Install Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.19

      - name: Install Melos
        run: dart pub global activate melos

      - name: Install CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: ~3.26.0

      - name: Install ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ci-${{ runner.os }}

      - run: melos format:check
      - run: melos bootstrap
      - run: melos analyze
      - run: melos build:OpenSSL
      - run: melos build:libCouchbaseDart
      - run: melos initCouchbaseServer
      - run: melos test
