name: Publish couchbase package

permissions:
  # This is required for uploading release artifacts.
  contents: write
  # This is required for authentication with pub.dev using OIDC.
  id-token: write

on:
  push:
    tags:
      - 'couchbase-v*'
  workflow_dispatch:

jobs:
  macOS:
    strategy:
      matrix:
        arch: [x86_64, arm64]
    runs-on: macos-latest
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.2

      - name: Install Melos
        run: dart pub global activate melos

      - name: Install CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: ~3.26.0

      - name: Install ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: release-binaries-macos-${{ matrix.arch }}

      - run: melos build:OpenSSL -- --arch ${{ matrix.arch }}

      - run: melos build:libCouchbaseDart
        env:
          CMAKE_OSX_ARCHITECTURES: ${{ matrix.arch }}

      - name: Create archive
        working-directory: native/build
        run:
          # Use GNU tar to work around a bug in Apple tar.
          # https://github.com/actions/runner-images/issues/2619
          gtar -czf libCouchbaseDart-macos-${{ matrix.arch }}.tar.gz
          libCouchbaseDart.dylib

      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: libCouchbaseDart-macos-${{ matrix.arch }}
          path: native/build/libCouchbaseDart-macos-${{ matrix.arch }}.tar.gz

  Linux:
    strategy:
      matrix:
        include:
          - runner: ubuntu-22.04
            arch: x86_64
          - runner: ubuntu-22.04-arm
            arch: arm64
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.2

      - name: Install Melos
        run: dart pub global activate melos

      - name: Install CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: ~3.26.0

      - name: Install ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: release-binaries-linux-${{ matrix.arch }}

      - run: melos build:OpenSSL

      - run: melos build:libCouchbaseDart

      - name: Create archive
        working-directory: native/build
        run:
          tar -czf libCouchbaseDart-linux-${{ matrix.arch }}.tar.gz
          libCouchbaseDart.so

      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: libCouchbaseDart-linux-${{ matrix.arch }}
          path: native/build/libCouchbaseDart-linux-${{ matrix.arch }}.tar.gz

  Publish:
    if:
      github.event_name == 'push' && startsWith(github.ref,
      'refs/tags/couchbase-v')
    needs: [macOS, Linux]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all binary archives
        uses: actions/download-artifact@v4
        with:
          path: archives

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: archives/**

      - name: Install Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.2

      - name: Install dependencies
        working-directory: packages/couchbase
        run: dart pub get

      - name: Publish package
        working-directory: packages/couchbase
        run: dart pub publish --force
