name: Release binaries

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  macOS:
    strategy:
      matrix:
        arch: [x86_64, arm64]
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install Melos
        run: dart pub global activate melos

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Install ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: 2048M
          key: ci-ccache-${{ runner.os }}

      - run: melos build:OpenSSL -- --arch ${{ matrix.arch }}

      - run: melos build:libCouchbaseDart
        env:
          CMAKE_OSX_ARCHITECTURES: ${{ matrix.arch }}

  Linux:
    strategy:
      matrix:
        arch: [amd64, arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        uses: docker/build-push-action@v4
        with:
          platforms: linux/${{ matrix.arch }}
          context: native