name: Release binaries

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  macOS:
    strategy:
      matrix:
        arch: [x86_64, arm64]
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install Melos
        run: dart pub global activate melos

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Install ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: 2048M
          key: ci-ccache-${{ runner.os }}

      - run: melos build:OpenSSL -- --arch ${{ matrix.arch }}

      - run: melos build:libCouchbaseDart
        env:
          CMAKE_OSX_ARCHITECTURES: ${{ matrix.arch }}

  Linux:
    strategy:
      matrix:
        runner: [ubuntu-22.04, buildjet-4vcpu-ubuntu-2204-arm]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install Melos
        run: dart pub global activate melos

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Install ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: 2048M
          key: ci-ccache-${{ runner.os }}

      - run: melos build:OpenSSL

      - run: melos build:libCouchbaseDart
